### ISSUE TITLE
Failover BIG-IP Templates have multiple DO inline components

### ISSUE THREAD

**Issue by thnguyenf5** [F5Networks/f5-azure-arm-templates-v2#22] opened 2022-12-07 23:12 UTC
## Describe the bug
Failover BIG-IP Templates have multiple DO inline components - second DO declaration doesn't have License declaration

In https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/main/examples/failover/bigip-configurations/runtime-init-conf-3nic-byol-instance01-with-app.yaml, there are multiple DO declarations.  This is the same for the byol with apps and no apps.

Line 17 of the YAML file and also line 192 of the YAML file both have DO declarations defined inline.  

 
## Expected behavior
Licensing information deployed with DO declaration.

 
## Current behavior
Deployment fails.  

 
## Possible solution
Insert License components?

 
## Steps to reproduce
 

 
1. Clicked on Deploy to Azure via portal 
2. Filled out parameters
3. Pointed to copy of the github YAML files
4. Deployment failed due to lack of license file (DO starting in 192 has no license file declaration)
 

 
## Context
 
Trying to deploy HA pair of BIG-IP with AWAF policy.
 
## Your Environment
 
Deploying templates to existing Azure environment.
 
- Version used: BIGIP 16.1.302000 BYOL

**Comment by mikeshimkus** [comment] 2022-12-08 00:05
Hi @thnguyenf5, this is by design. The 2nd DO declaration includes the cluster configuration, which needs to run last on both devices in order to clustering to work reliably. The license configuration is not required in the 2nd DO configuration since once the device is licensed, DO will never revoke a license.

**Comment by shyawnkarim** [comment] 2023-04-10 20:11
Closing. Please open another issue if you would like additional assistance.

**Closed by shyawnkarim** 2023-04-10 20:11 UTC
Labels: help wanted
